### ISSUE TITLE
Error with authentication

### ISSUE THREAD

**Issue by dlfreriks** [johsund/QlikSocial#1]
This site can’t be reached

localhost refused to connect.
Search Google for localhost 3000 auth
ERR_CONNECTION_REFUSED

Followed all the steps.  Launches but crashes with the error above.

Qlik Webconnector (check)
Nodejs (check)
Virtual Proxy (check)

**Comment by dlfreriks** [comment]
Example app listening on port 3000!
undefined:1
Couldn&#39;t find virtual proxy derived from targetId
^

SyntaxError: Unexpected token C
    at Object.parse (native)
    at Request._callback (C:\QlikSocial\QlikSocial-master\index.js:46:25)
    at Request.self.callback (C:\QlikSocial\QlikSocial-master\node_modules\reque
st\request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\QlikSocial\QlikSocial-master\node_modules\request
\request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\QlikSocial\QlikSocial-master\node_modules
\request\request.js:988:12)
    at emitNone (events.js:72:20)

**Comment by dlfreriks** [comment]
Duh - didn't link the proxy...
